# 
# Makefile
# 
# Copyright (C) 2015 ETH Zurich, University of Bologna
# All rights reserved.
# 

PULP_APP = aes_cpu
PULP_APP_SRCS = aes_demo.c aes.c
PULP_INC_PATHS += $(CURDIR)
PULP_CFLAGS = -O2 -g
PULP_LFLAGS = -O2 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
