#!/bin/bash

RET=""
for var in "$@"
do
if [[ $var == -* ]]
then
RET="${RET}$var "
else
re='\$::env\(([^)]*).*'
while [[ $var =~ $re ]]; do
  var="\$${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
done
RET="${RET}\""
RET="${RET}$var"
RET="${RET}\" "
fi
done

#echo "$RET"

sshpass -f ~/eda03 ssh sjaeger@eda03.ict.tuwien.ac.at "cd $(pwd) && vlib $RET"

