###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID eda03.ict.tuwien.ac.at)
#  Generated on:      Thu Aug 11 14:37:21 2022
#  Design:            aes_cipher_top
#  Command:           create_ccopt_clock_tree_spec -filename ccopt_aes.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clock (period 3.000ns) in timing_config TSMC65G_cm([aes_cipher_top.sdc])
create_ccopt_clock_tree -name clock -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner TSMC65G_dc -early -clock_tree clock 0.250

set_ccopt_property target_max_trans_sdc -delay_corner TSMC65G_dc -late -clock_tree clock 0.250
# Clock period setting for source pin of clock
set_ccopt_property clock_period -pin clk 3

# Skew group to balance non generated clock:clock in timing_config:TSMC65G_cm (sdc aes_cipher_top.sdc)
create_ccopt_skew_group -name clock/TSMC65G_cm -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clock/TSMC65G_cm true
set_ccopt_property target_insertion_delay -skew_group clock/TSMC65G_cm 0.100
set_ccopt_property extracted_from_clock_name -skew_group clock/TSMC65G_cm clock
set_ccopt_property extracted_from_constraint_mode_name -skew_group clock/TSMC65G_cm TSMC65G_cm
set_ccopt_property extracted_from_delay_corners -skew_group clock/TSMC65G_cm TSMC65G_dc


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

